#Classification Problems

##K-nearest neighber

In [16]:
import numpy as np
def knn(inX, dataSet,labels,k):
    dataSetSize=dataSet.shape[0]
    print dataSetSize
    diffMat=np.tile(inX,(dataSetSize,1))-dataSet
    sqDiffMat=diffMat**2
    sqDistances=sqDiffMat.sum(axis=1)
    distances=sqDistances**0.5
    sortedDistIndicies=distances.argsort()
    classCount={}
    for i in range(k):
        voteIlabel=labels[sortedDistIndices[i]]
        classCount[voteIlabel]=classCount.get(voteIlabel,0)+1
    sortedClassCount=sorted(classCount.iteritems(),
     key=operater.itemgetter(1),reverse=True)
    return sortedClassCount[0][0]
    

In [26]:
inX=x[test]
dataSet=x[train]
labels=y[train]
k=5

dataSetSize=dataSet.shape[0]
print dataSetSize
print np.tile(inX,(dataSetSize,1)).shape
print dataSet.shape
print inX.shape
diffMat=np.tile(inX,(dataSetSize,1))-dataSet
print diffMat.shape,diffMat[:5]
sqDiffMat=diffMat**2
print sqDiffMat.shape,sqDiffMat[:5]
sqDistances=sqDiffMat.sum(axis=1)
distances=sqDistances**0.5
sortedDistIndicies=distances.argsort()
classCount={}
print 'k:',k
for i in range(k):
    voteIlabel=labels[sortedDistIndicies[i]]
    classCount[voteIlabel]=classCount.get(voteIlabel,0)+1
sortedClassCount=sorted(classCount.iteritems(),
 key=operater.itemgetter(1),reverse=True)
return sortedClassCount[0][0]

1
(149L, 4L)
(1L, 4L)
(149L, 4L)
(149L, 4L) [[ 0.3  0.5  0.   0.1]
 [ 0.1  0.   0.   0.1]
 [-0.1  0.2 -0.1  0.1]
 [-0.2  0.1  0.1  0.1]
 [ 0.2  0.6  0.   0.1]]
(149L, 4L) [[ 0.09  0.25  0.    0.01]
 [ 0.01  0.    0.    0.01]
 [ 0.01  0.04  0.01  0.01]
 [ 0.04  0.01  0.01  0.01]
 [ 0.04  0.36  0.    0.01]]
k: 5


IndexError: index 1 is out of bounds for axis 0 with size 1

In [22]:
from sklearn.datasets import load_iris
import random
iris=load_iris()
x=iris.data
y=iris.target
train=random.sample(range(len(y)),1)
test=np.delete(range(len(y)),train)
print train,test

[12] [  0   1   2   3   4   5   6   7   8   9  10  11  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149]


In [5]:
result=knn(inX=x[test],dataSet=x[train],labels=y[train],k=5)

ValueError: operands could not be broadcast together with shapes (3600,4) (120,4) 