In [28]:
import numpy as np
a=np.random.uniform(-1,1,size=(3,3))
print a

[[-0.73778522  0.56366535 -0.16823617]
 [-0.06745925 -0.26284131 -0.51306408]
 [-0.39960415  0.78005752 -0.98593099]]


In [12]:

b=a
print b


[[ 1.          0.42590919 -0.84723955]
 [ 0.40604524 -0.7864208   0.22322146]
 [-0.62680888 -0.01227018 -0.73190694]]


In [13]:
b[0,0]=2
print b

[[ 2.          0.42590919 -0.84723955]
 [ 0.40604524 -0.7864208   0.22322146]
 [-0.62680888 -0.01227018 -0.73190694]]


In [15]:
a=np.empty((3,3))
print a

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [16]:
np.ones_like(a)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
b = np.full((2,3),2)

In [24]:
d,f=np.nonzero(b)
for i in zip(d,f):
    print b[i]

2.0
2.0
2.0
2.0
2.0
2.0


In [30]:
print a
np.where(a>0)

[[-0.73778522  0.56366535 -0.16823617]
 [-0.06745925 -0.26284131 -0.51306408]
 [-0.39960415  0.78005752 -0.98593099]]


(array([0, 2], dtype=int64), array([1, 1], dtype=int64))