In [4]:
from numpy import *
n=([[1,2,3],[4,5,6]])

In [22]:
a= arange(30).reshape(3,5,2)
type(a)
a.shape
a.ndim
a.dtype.name
a.size
b=array([1,2,3])
type(b)
b

array([1, 2, 3])

In [29]:
b=array([(1,2,4),(2.,3.,4.)],dtype=complex)
b
b.shape
b.ndim
b.size
b.dtype
b.dtype.name

'complex128'

In [38]:
##zeros create matrix all zeros
c=zeros((3,4))
c
##ones create matrix all ones
d=ones((2,3),dtype=int64)
d
print c
print d

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1]
 [1 1 1]]


In [41]:
##arange offer a sequence given jump (from ,to, jump)
arange(10,30,5)
##linesapce offer a sequence given number(from ,to ,number)
linspace(0,2,3)


array([ 0.,  1.,  2.])

In [50]:
set_printoptions(threshold='nan')
print arange(100).reshape(10,10)

[[ 0  1  2 ...,  7  8  9]
 [10 11 12 ..., 17 18 19]
 [20 21 22 ..., 27 28 29]
 ..., 
 [70 71 72 ..., 77 78 79]
 [80 81 82 ..., 87 88 89]
 [90 91 92 ..., 97 98 99]]


In [62]:
a=array([20,30,40,50])
b=arange(4)
b
c=a-b
c
print b*2
print b**2

10*sin(a)
index=a<35
a[index]

[0 2 4 6]
[0 1 4 9]


array([20, 30])

In [68]:
a=arange(0,4,1).reshape(2,2)
b=arange(5,9,1).reshape(2,2)
#print a,b
##element wise
a*b
##matrix dot
dot(a,b)

array([[ 7,  8],
       [31, 36]])

In [73]:
a.sum()
a.min()
a.max()

c=random.random((2,3))
c

array([[ 0.28966403,  0.99929073,  0.83654665],
       [ 0.50846865,  0.96084399,  0.35329652]])

In [80]:
##axis=0 means sum each column
print a
a.sum(axis=0)
a.min(axis=1)
a.cumsum(axis=1).cumsum(axis=1)
##each row

[[0 1]
 [2 3]]


array([[0, 1],
       [2, 7]])

In [86]:
##universal functions
b=arange(0,4).reshape(2,2)
exp(b)
sqrt(b)
c=arange(10,14,1).reshape(2,2)
b+c

array([[10, 12],
       [14, 16]])

In [95]:
a=arange(10)**2
print a
a[2] ##3rd
a[2:5] ##exclusive
a[0:6:2]=-100 ##for every two elements set the 2nd -100
##from 0 to 6 exclusive
print a
a[::-1]##inverse a

[ 0  1  4  9 16 25 36 49 64 81]
[-100    1 -100    9 -100   25   36   49   64   81]


array([  81,   64,   49,   36,   25, -100,    9, -100,    1, -100])