##Getting sample data from the example


In [ ]:
from sklearn import datasets
import numpy as np

In [5]:
boston=datasets.load_boston()
print boston.DESCR

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [6]:
housing=datasets.fetch_california_housing()
print housing.DESCR

downloading Cal. housing from http://lib.stat.cmu.edu/modules.php?op=modload&name=Downloads&file=index&req=getit&lid=83 to C:\Users\zc\scikit_learn_data
California housing dataset.

The original database is available from StatLib

    http://lib.stat.cmu.edu/

The data contains 20,640 observations on 9 variables.

This dataset contains the average house value as target variable
and the following input variables (features): average income,
housing average age, average rooms, average bedrooms, population,
average occupation, latitude, and longitude in that order.

References
----------

Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
Statistics and Probability Letters, 33 (1997) 291-297.




In [7]:
import sklearn.datasets as d
import numpy as np

In [8]:
d.make_*?

In [18]:
d.make_regression?

In [19]:
data=d.make_regression(1000,10,5,2,1.0)

##scaling data to the standard normal

In [20]:
from sklearn import preprocessing
import numpy as np

In [22]:
n_samples=1000
n_features=10
X = np.random.randn(n_samples, n_features)

In [27]:
print X[:,:3].mean(axis=0)
print X[:,:3].std(axis=0)

[ 0.00922185  0.04986512  0.02615653]
[ 0.98663811  1.02358573  0.98750061]


In [34]:
X2=preprocessing.scale(X[:,:3])
X2.mean(axis=0)
X2.std(axis=0)

array([ 1.,  1.,  1.])

In [47]:
minmax_scaler=preprocessing.MinMaxScaler()
minmax_scaler.fit(X[:,:3])
x3=minmax_scaler.transform(X[:,:3])
x3.max(axis=0)
x3.min(axis=0)

array([ 0.,  0.,  0.])

In [48]:
##another scaler
other_range=preprocessing.MinMaxScaler(feature_range=(-3.14,3.14))
other_range.fit(X[:,:3])
x4=other_range.transform(X[:,:3])
x4.max(axis=0)

array([ 3.14,  3.14,  3.14])

In [53]:
##normalization scale each sample to have a length of 1
normalized_x=preprocessing.normalize(X[:,:3])


##creating bianry feature through thresholding


In [1]:
from sklearn import datasets
boston=datasets.load_boston()
import numpy as np


In [11]:
from sklearn import preprocessing
new_target=preprocessing.binarize(boston.target,threshold=boston.target.mean())

bin=preprocessing.Binarizer(boston.target.mean())
new_target=bin.fit_transform(boston.target)
print new_target[0:]

[[ 1.  0.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.
   0.  1.  1.  1.  1.  0.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  1.  0.
   1.  1.  1.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  0.  0.  1.  1.
   1.  0.  1.  1.  0.  1.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  0.  0.  0.  0.  1.  1.  1.
   1.  1.  0.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  0.  0.  0. 

##working with categoritcal variables

In [17]:
from sklearn import datasets
iris=datasets.load_iris()
#print iris.DESCR
X=iris.data
y=iris.target
import numpy as np
d=np.column_stack((X,y))

In [22]:
from sklearn import preprocessing
text_encoder=preprocessing.OneHotEncoder()
text_encoder.fit_transform(d[:,-1:]).toarray()

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

##DictVectorizer
another option is to use dictVectorizer.this can be used to directly convert strings to features:


In [31]:
from sklearn.feature_extraction import DictVectorizer
dv=DictVectorizer()
my_dict=[{'species':iris.target_names[i]} for i in y]
index=[1,50,120]
dv.fit_transform(my_dict).toarray()[index]

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

##Binarizing label features

In [34]:
from sklearn import datasets as d
iris=d.load_iris()
target=iris.target

In [37]:
from sklearn.preprocessing import LabelBinarizer
label_binarizer=LabelBinarizer()
new_target=label_binarizer.fit_transform(target)
new_target.shape

(150L, 3L)

###more on binarize
0 and 1 are ont only way to represent positive instance and negtiveinstance

In [39]:
label_binarizer=LabelBinarizer(neg_label=-3,pos_label=3)
label_binarizer.fit_transform(target)

array([[ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -3, -3],
       [ 3, -

##imputing missing values through various strategies

In [42]:
from sklearn import datasets
import numpy as np
iris=datasets.load_iris()
X=iris.data
masking_array=np.random.binomial(1,0.25,X.shape).astype(bool)
X[masking_array]=np.nan
masking_array[:5]
X[:5]

array([[ 5.1,  3.5,  1.4,  nan],
       [ 4.9,  3. ,  nan,  nan],
       [ 4.7,  3.2,  1.3,  0.2],
       [ nan,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [46]:
from sklearn import preprocessing
impute=preprocessing.Imputer(strategy='median')
iris_X=impute.fit_transform(X)
iris_X[:5]

array([[ 5.1,  3.5,  1.4,  1.3],
       [ 4.9,  3. ,  4.4,  1.3],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 5.7,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [52]:
impute2=preprocessing.Imputer(missing_values=1)
iris_X2=impute2.fit_transform(X)
iris_X2[:5]

array([], shape=(5L, 0L), dtype=float64)

##Using pipelines for multiple preprocessing steps

In [53]:
from sklearn import datasets
import numpy as np
mat=datasets.make_spd_matrix(10)
masking_array=np.random.binomial(1,.1,mat.shape).astype(bool)
mat[:4,:4]

array([[ 1.13471645, -0.23636519,  0.13670053,  0.36800488],
       [-0.23636519,  0.87356802, -0.06830902, -0.18464931],
       [ 0.13670053, -0.06830902,  0.67469696,  0.02815677],
       [ 0.36800488, -0.18464931,  0.02815677,  1.19726575]])

In [54]:
from sklearn import preprocessing
impute=preprocessing.Imputer()
scaler=preprocessing.StandardScaler()
from sklearn import pipeline
pipe=pipeline.Pipeline([('impute',impute),('scaler',scaler)])
pipe

Pipeline(steps=[('impute', Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)), ('scaler', StandardScaler(copy=True, with_mean=True, with_std=True))])

In [56]:
##call the fit_transform method on the pipe object
##these separate steps are completed in a single step:
new_mat=pipe.fit_transform(mat)
new_mat[:4,:4]

array([[  1.43912342e+00,  -4.18549110e-01,   1.71032643e-03,
          1.66914669e-01],
       [ -7.63439265e-01,   1.93608863e+00,  -7.57480703e-01,
         -6.83277439e-01],
       [ -1.64130943e-01,  -6.20309055e-02,   1.99401779e+00,
         -3.55900836e-01],
       [  2.07445997e-01,  -3.08837853e-01,  -4.00248740e-01,
          1.44263296e+00]])

##Reducing dimensionality with PCA

In [57]:
from sklearn import datasets
iris=datasets.load_iris()
iris_X=iris.data

In [59]:
from sklearn import decomposition
pca=decomposition.PCA()
pca

PCA(copy=True, n_components=None, whiten=False)

In [60]:
iris_pca=pca.fit_transform(iris_X)
iris_pca[:5]

array([[ -2.68420713e+00,  -3.26607315e-01,   2.15118370e-02,
          1.00615724e-03],
       [ -2.71539062e+00,   1.69556848e-01,   2.03521425e-01,
          9.96024240e-02],
       [ -2.88981954e+00,   1.37345610e-01,  -2.47092410e-02,
          1.93045428e-02],
       [ -2.74643720e+00,   3.11124316e-01,  -3.76719753e-02,
         -7.59552741e-02],
       [ -2.72859298e+00,  -3.33924564e-01,  -9.62296998e-02,
         -6.31287327e-02]])

In [61]:
pca.explained_variance_ratio_

array([ 0.92461621,  0.05301557,  0.01718514,  0.00518309])

In [62]:
pca=decomposition.PCA(n_components=2)
iris_X_prime=pca.fit_transform(iris_X)
iris_X_prime.shape

(150L, 2L)

In [63]:
##pca explain at least 98 percent of the variance
pca=decomposition.PCA(n_components=.98)
iris_X_prime=pca.fit(iris_X)
pca.explained_variance_ratio_.sum()

0.99481691454980992

##Using factor analysis for decomposition

In [65]:
from sklearn.decomposition import FactorAnalysis
from sklearn import datasets
iris=datasets.load_iris()

In [69]:
fa=FactorAnalysis(n_components=2)
iris_two_dim=fa.fit_transform(iris.data)
iris_two_dim[:5]

array([[-1.33125848,  0.55846779],
       [-1.33914102, -0.00509715],
       [-1.40258715, -0.307983  ],
       [-1.29839497, -0.71854288],
       [-1.33587575,  0.36533259]])

##Kennel PCA for nonlinear dimensionality reduction

In [72]:
import numpy as np
A1_mean=[1,1]
A1_cov=[[2,.99],[1,1]]
A1=np.random.multivariate_normal(A1_mean,A1_cov,50)

A2_mean=[5,5]
A2_cov=[[2,.99],[1,1]]
A2=np.random.multivariate_normal(A2_mean,A2_cov,50)

A=np.vstack((A1,A2))

B_mean=[5,0]
B_cov=[[.5,-1],[-.9,.5]]
B=np.random.multivariate_normal(B_mean,B_cov,100)

C:\Users\zc\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\kernel\__main__.py:14: RuntimeWarning: covariance is not positive-semidefinite.


In [77]:
kpca=decomposition.KernelPCA(kernel='cosine',n_components=1)
AB=np.vstack((A,B))
AB_transformed=kpca.fit_transform(AB)

##Using truncated SVD to reduce dimensionality

In [78]:
from sklearn.datasets import load_iris
iris=load_iris()

In [79]:
from sklearn.decomposition import TruncatedSVD
svd=TruncatedSVD(2)
iris_tran=svd.fit_transform(iris.data)
print iris.data[:5]
print iris_tran[:5]

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]
[[ 5.91220352 -2.30344211]
 [ 5.57207573 -1.97383104]
 [ 5.4464847  -2.09653267]
 [ 5.43601924 -1.87168085]
 [ 5.87506555 -2.32934799]]


In [83]:
##using scipy to learn svd process
from scipy.linalg import svd
import numpy as np
D=np.array([[1,2],[1,3],[1,4]])
D

array([[1, 2],
       [1, 3],
       [1, 4]])

In [84]:
U,S,V=svd(D, full_matrices=False)
print U.shape,S.shape,V.shape

(3L, 2L) (2L,) (2L, 2L)


In [85]:
np.dot(U.dot(np.diag(S)),V)

array([[ 1.,  2.],
       [ 1.,  3.],
       [ 1.,  4.]])

In [86]:
#if we want to simulate the truncation, we will drop 
#the smallest singular values and the corresponding 
##column vectors of U. 
new_S=S[0]
new_U=U[:,0]
new_U.dot(new_S)

array([-2.20719466, -3.16170819, -4.11622173])

##Decomposition to classify with DictionaryLearning

DictionaryLearning attempts to take a dataset and transform
it into a sparse representation.

In [92]:
from sklearn.datasets import load_iris
iris=load_iris()


In [93]:
from sklearn.decomposition import DictionaryLearning
dl=DictionaryLearning(3)
transformed=dl.fit_transform(iris.data[::2])
transformed[:5]

array([[ 0.        ,  6.34476574,  0.        ],
       [ 0.        ,  5.83576461,  0.        ],
       [ 0.        ,  6.32038375,  0.        ],
       [ 0.        ,  5.89318572,  0.        ],
       [ 0.        ,  5.45222715,  0.        ]])

##Putting it all together with Pipelines

In [ ]:
from skelearn.datasets import load_iris
import numpy as np

In [94]:
iris=load_iris()
iris_data=iris.data
mask=np.random.binomial(1,.25,iris_data.shape).astype(bool)
iris_data[mask]=np.nan
iris_data[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ nan,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  nan,  0.2],
       [ 4.6,  nan,  1.5,  0.2],
       [ 5. ,  nan,  1.4,  0.2]])

In [95]:
from sklearn import pipeline,preprocessing,decomposition

##create the imputer and pca classes
pca=decomposition.PCA()
imputer=preprocessing.Imputer()

In [97]:
##create a pipe line
pipe=pipeline.Pipeline([('imputer',imputer),('pca',pca)])
iris_data_transformed=pipe.fit_transform(iris_data)
iris_data_transformed[:5]

array([[-2.69552892,  0.02925068,  0.24571523,  0.2216217 ],
       [-2.46034731, -0.56692907,  0.29427252, -0.3890228 ],
       [-0.64943393,  1.192394  ,  0.72911798,  0.14641949],
       [-2.70092101,  0.59427419,  0.0493901 , -0.13929987],
       [-2.68455342,  0.19465465,  0.11210702, -0.217421  ]])