In [1]:
import numpy as np

def polykernel(x,y):
    sum=0
    for i in range(len(x)):
        sum+=x[i]*y[i]
    return (sum)**2

In [2]:
def cosinekernel(x,y):
    return (1./(np.linalg.norm(x)*np.linalg.norm(y)))*np.dot(x,y)

In [67]:
def kpca(data):
    #data=data.T
    N=data.shape[0]
    K=np.zeros((N,N))
    #print K
    for i in range(N):
        for j in range(N):
            K[i,j]=cosinekernel(data[i,],data[j,])
    ones=1./N*np.ones((N,N))
    # Don't forget to center the data!!!
    K_norm=K-np.dot(ones,K)-np.dot(K,ones)+np.dot(ones,np.dot(K,ones))
    U,E,VT = np.linalg.svd(K_norm)
    tmp = np.dot(U,np.diag(np.sqrt(E)))
    return tmp[:,:4]


In [68]:
data=np.random.randint(0,20,size=(5,4))
print data

[[14  5  6 17]
 [ 5  6 10  4]
 [ 6 14 11  8]
 [16  0 15 16]
 [11 13 19 13]]


In [69]:
A=kpca(data)
print A


[[-0.3811497   0.20379142 -0.00756316  0.01109886]
 [ 0.25419173 -0.1553072  -0.03098518  0.01303569]
 [ 0.33034688  0.17387273 -0.01000528 -0.01555935]
 [-0.35368787 -0.1847956  -0.00198643 -0.01457496]
 [ 0.15029896 -0.03756136  0.05054005  0.00599976]]


In [70]:
B=kpca(np.transpose(data))
print B

[[ -3.20084601e-01  -3.16608155e-02  -2.92161077e-02   4.93437368e-09]
 [  5.37564842e-01  -1.05130818e-01  -4.48263602e-03   4.93437368e-09]
 [  5.59479396e-02   2.54369320e-01   6.89870141e-03   4.93437368e-09]
 [ -2.73428180e-01  -1.17577687e-01   2.68000424e-02   4.93437368e-09]]


In [71]:
from sklearn import decomposition
kp=decomposition.KernelPCA(kernel='cosine',n_components=4)
C = kp.fit_transform(data)
print C

[[ 0.3811497  -0.20379142  0.00756316  0.01109886]
 [-0.25419173  0.1553072   0.03098518  0.01303569]
 [-0.33034688 -0.17387273  0.01000528 -0.01555935]
 [ 0.35368787  0.1847956   0.00198643 -0.01457496]
 [-0.15029896  0.03756136 -0.05054005  0.00599976]]


In [72]:
print A
print C
print A/C

[[-0.3811497   0.20379142 -0.00756316  0.01109886]
 [ 0.25419173 -0.1553072  -0.03098518  0.01303569]
 [ 0.33034688  0.17387273 -0.01000528 -0.01555935]
 [-0.35368787 -0.1847956  -0.00198643 -0.01457496]
 [ 0.15029896 -0.03756136  0.05054005  0.00599976]]
[[ 0.3811497  -0.20379142  0.00756316  0.01109886]
 [-0.25419173  0.1553072   0.03098518  0.01303569]
 [-0.33034688 -0.17387273  0.01000528 -0.01555935]
 [ 0.35368787  0.1847956   0.00198643 -0.01457496]
 [-0.15029896  0.03756136 -0.05054005  0.00599976]]
[[-1. -1. -1.  1.]
 [-1. -1. -1.  1.]
 [-1. -1. -1.  1.]
 [-1. -1. -1.  1.]
 [-1. -1. -1.  1.]]
